#!/usr/bin/env fish

if not set -q IN_DEVCONTAINER || not set -q WIRE_WORKSPACE || not set -q CC || not set -q CXX  
    echo "This script is meant to be run inside the devcontainer. Please run './scripts/devcontainer-setup' first."
    exit 255
end

set -gx WIRE_PREFIX $HOME/.local
set -gx wireDevContainerBinDir (dirname (realpath (status filename)))
set -gx wireDevContainerRoot (dirname $wireDevContainerBinDir)
set -gx wireRepoRoot (realpath (dirname $wireDevContainerRoot))
set -gx wireOPPRoot $wireRepoRoot/wire-sysio/build/opp

set -g _wireDefaultRepos wire-sysio wire-cdt wire-libraries-ts wire-e2e-tests wire-ethereum wire-solana wire-vcpkg-registry

if not set -q TASK_CPUS
		set -gx TASK_CPUS 4
end
set -gx cpuCount (math ceil\( $TASK_CPUS / 2 \) )

function die
    echo "$argv[1]"
    exit 255
end

function run
    set cmd $argv
    eval "$cmd"; or die "An error occurred while executing: $cmd"
end

function set-default
    set newValue $argv[1]
    set -q $newValue
    and echo $newValue
    or echo $argv[2]
end

function set-or-default
    set newValue $argv[1]
    if test -z $newValue
        set $newValue $argv[2]
    end
end

run npm i -g @protobuf-ts/plugin
run pnpm i -g @protobuf-ts/plugin

run pushd $wireRepoRoot/wire-cdt
run ./vcpkg/bootstrap-vcpkg.sh

run cmake \
      -G Ninja \
      -DENABLE_CCACHE=ON \
      -DENABLE_DISTCC=OFF \
      -DENABLE_TESTS=ON \
      -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_MAKE_PROGRAM=(which ninja) \
      -DCMAKE_C_COMPILER=$CC \
      -DCMAKE_CXX_COMPILER=$CXX \
      -DCMAKE_INSTALL_PREFIX=$WIRE_PREFIX \
      -DCMAKE_PREFIX_PATH=$WIRE_PREFIX \
      -DCMAKE_PARALLEL_LEVEL=$cpuCount \
      -S . \
      -B build/debug

run cmake --build build/debug -j$cpuCount --target all
run cmake --install build/debug
popd

# Build wire-sysio
run pushd $wireRepoRoot/wire-sysio
run ./vcpkg/bootstrap-vcpkg.sh

run cmake \
      -G Ninja \
      -DENABLE_CCACHE=ON \
      -DENABLE_DISTCC=OFF \
      -DENABLE_TESTS=ON \
      -DBUILD_OPP_BUNDLES=ON \
      -DBUILD_SYSTEM_CONTRACTS=ON \
      -DBUILD_TEST_CONTRACTS=ON \
      -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
      -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
      -DCMAKE_BUILD_TYPE=Debug \
      -DCMAKE_C_COMPILER=$CC \
      -DCMAKE_CXX_COMPILER=$CXX \
      -DCMAKE_MAKE_PROGRAM=(which ninja) \
      -DCMAKE_INSTALL_PREFIX=$WIRE_PREFIX \
      -DCMAKE_PREFIX_PATH=$WIRE_PREFIX/cdt \
      -DCMAKE_PARALLEL_LEVEL=$cpuCount \
      -S . \
      -B build/debug

run cmake --build build/debug -j$cpuCount --target all

popd

if not test -d $wireOPPRoot/typescript -a -d $wireOPPRoot/solidity
	die "ERROR: wire-opp bundles not generated"
end

echo "wire-opp bundles found, proceeding with installation/linking"
run cd $wireOPPRoot/typescript
run pnpm i --force --no-frozen-lockfile
run npm link
run cd $wireOPPRoot/solidity
run pnpm i --force --no-frozen-lockfile
run npm link

# Build and install wire-libraries-ts
echo "Building & Linking wire-libraries-ts"
run pushd $wireRepoRoot/wire-libraries-ts

run pnpm install --no-frozen-lockfile
run pnpm run build
run pnpm install

run popd

echo "Building & Linking wire-e2e-tests"
run cd $wireRepoRoot/wire-e2e-tests
run pnpm i --force --no-frozen-lockfile
run pnpm run build
run pushd $wireRepoRoot/wire-e2e-tests/packages/test-cluster-tool
run pnpm link --global
run pushd $wireRepoRoot/wire-e2e-tests/packages/debugging-server
run pnpm link --global

echo "Building & Linking wire-ethereum"
run cd $wireRepoRoot/wire-ethereum
run npm i
run npm link @wireio/opp-solidity-models
run npm run build
run npx hardhat compile

echo "Building & Linking wire-solana"
run cd $wireRepoRoot/wire-solana
run cargo build

