#!/usr/bin/env fish

if not set -q IN_DEVCONTAINER || not set -q WIRE_WORKSPACE || not set -q CC || not set -q CXX  
    echo "This script is meant to be run inside the devcontainer. Please run './scripts/devcontainer-setup' first."
    exit 255
end

set -gx WIRE_PREFIX $HOME/.local
set -gx wireDevContainerBinDir (dirname (realpath (status filename)))
set -gx wireDevContainerRoot (dirname $wireDevContainerBinDir)
set -gx wireRepoRoot (realpath (dirname $wireDevContainerRoot))
set -gx wireOPPRoot $wireRepoRoot/wire-sysio/build/opp

set -g _wireDefaultRepos wire-sysio wire-cdt wire-libraries-ts wire-tools-ts wire-ethereum wire-solana wire-vcpkg-registry

if not set -q TASK_CPUS
		set -gx TASK_CPUS 4
end
set -gx cpuCount (math ceil\( $TASK_CPUS / 2 \) )

function die
    echo "$argv[1]"
    exit 255
end

function run
    set cmd $argv
    eval "$cmd"; or die "An error occurred while executing: $cmd"
end

function set-default
    set newValue $argv[1]
    set -q $newValue
    and echo $newValue
    or echo $argv[2]
end

function set-or-default
    set newValue $argv[1]
    if test -z $newValue
        set $newValue $argv[2]
    end
end

set wireSetupScript "$wireDevContainerBinDir/wire-local-setup.bash"
if not test -e $wireSetupScript
	die "$wireSetupScript is missing"
end

set wireSetupCmd $wireSetupScript \
	--skip-apt \
	--skip-clone \
	--ignore-docker \
	$wireRepoRoot

echo "Starting: $wireSetupCmd"
run $wireSetupCmd